on: [push]

jobs:
  test_action:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test action
        uses: ./ # Uses an action in the root directory
        id: hello
        with:
          cookie: ''
          version: '0.4'
          token: ${{ secrets.GITHUB_TOKEN }}