on: [push]

jobs:
  test_action:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test action
        uses: ./ # Uses an action in the root directory
        with:
          cookie: $$ {{ secrets.ROBLOSECURITY }}
          token: ${{ secrets.GITHUB_TOKEN }}